name: test action trigger

on:   
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: print
        run: echo "Hello World from ${{ github.head_ref || github.ref_name }}!"
